# Generated by Django 5.1.3 on 2024-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Padding'), ('OFD', 'Out For Delivery'), ('D', 'Delivered')], default='P', max_length=13)),
            ],
        ),
    ]
