# Generated by Django 5.1.2 on 2024-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/prescriptions/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
