# Generated by Django 5.1.3 on 2024-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.URLField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('manufacturer', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('compositions', models.TextField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('uses', models.TextField(null=True)),
                ('side_effects', models.TextField(null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('reviews', models.TextField(null=True)),
                ('total_rating', models.IntegerField(default=0, null=True)),
                ('total_reviews', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
