# Generated by Django 5.1.3 on 2024-11-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
