# Generated by Django 5.1.2 on 2024-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='dosage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
