# Generated by Django 5.1.2 on 2024-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_quantity_alter_products_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.CharField(blank=True, choices=[('GM', 'General medicine'), ('HCP', 'Hair care product'), ('BCP', 'Baby care product')], max_length=30, null=True),
        ),
    ]
