# Generated by Django 5.1.2 on 2025-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=20, null=True)),
                ('availableDates', models.JSONField()),
                ('fees', models.IntegerField(default=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/doctorsPhoto/')),
            ],
        ),
    ]
