# Generated by Django 5.1.2 on 2024-12-01 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_last_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField(max_length=6)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2024, 12, 1, 16, 29, 26, 643763, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
