# Generated by Django 5.1.2 on 2024-12-01 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_otp_expiry_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 18, 3, 47, 861665, tzinfo=datetime.timezone.utc)),
        ),
    ]
