# Generated by Django 5.1.2 on 2024-12-07 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 18, 20, 10, 579401, tzinfo=datetime.timezone.utc)),
        ),
    ]
