# Generated by Django 5.1.2 on 2024-12-09 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 19, 56, 34, 110655, tzinfo=datetime.timezone.utc)),
        ),
    ]
