# Generated by Django 5.1.2 on 2024-12-14 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 14, 3, 57, 368061, tzinfo=datetime.timezone.utc)),
        ),
    ]
