# Generated by Django 5.1.2 on 2025-06-10 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 19, 4, 53, 260368, tzinfo=datetime.timezone.utc)),
        ),
    ]
