# Generated by Django 5.1.2 on 2025-06-10 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 19, 36, 16, 787343, tzinfo=datetime.timezone.utc)),
        ),
    ]
