# Generated by Django 5.1.2 on 2025-06-11 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 6, 20, 3, 63471, tzinfo=datetime.timezone.utc)),
        ),
    ]
