# Generated by Django 5.1.2 on 2025-06-16 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 18, 26, 14, 830800, tzinfo=datetime.timezone.utc)),
        ),
    ]
